### ISSUE TITLE
anyway to use beauty face filter feature

### ISSUE THREAD

**Issue by linhphan534** [aws-samples/amazon-ivs-broadcast-android-sample#1]
hi, I'm sorry that this isn't really an issue with your project but just my concern.
I reading up your sample project and your document, but I don't see any parts that can enable beauty face filter, I'm wondering is your sdk has any built-in api can handle that work? or can attached a third party library like faceunity to do that job.
I hope can receive your answer soon, please forgive me if I drop my my concern wrongly.
thanks.

**Comment by ysshin** [comment]
Hi @linhphan534,
We do not have built-in beauty face filter support yet. We are working on it but we don't have official timeline of the target release at this moment.
With our current broadcast sdk, you can do below to use a third party library
1. capture camera outside the SDK
2. apply filter using third party library
3. send that as source of custom input source
Hope this helps. Let us know if you have any more question!

**Comment by YD-APP-Contact** [comment]
> Hi @linhphan534, We do not have built-in beauty face filter support yet. We are working on it but we don't have official timeline of the target release at this moment. With our current broadcast sdk, you can do below to use a third party library
> 
> 1. capture camera outside the SDK
> 2. apply filter using third party library
> 3. send that as source of custom input source
>    Hope this helps. Let us know if you have any more question!

Hi, @ysshin 

1)Judging from the text, it is currently under development, right?
2) If first Q. is YES, It has been three months since your reply. Would you like to ask when the current development can expect this feature to be completed?


Hope you can answer the above question, Thank you. 

Our team that is using IVS Broadcast

**Comment by caleighm** [comment]
Hi @YD-APP-Contact,

Thanks for checking in. At this time, unfortunately we don't have an estimate for when a built-in beauty filter will be completed.

In the meantime, we recommend you use the custom input source method we mentioned earlier. That will unblock you. If you'd like extra support with this, please reach out to your IVS business contact so we can prioritize this and work with you directly.

Thanks!
