### ISSUE TITLE
setDefaultAspectMode for video in broadcastconfiguration is not public

### ISSUE THREAD

**Issue by 3embed007** [aws-samples/amazon-ivs-broadcast-android-sample#2]
Hi was trying to set the aspect ration of video to FILL instead of fit,but that methos seems to be private in code for sdk version 1.0.0,can you please help me?
Although as per docs,this method is public.

<img width="566" alt="Screen Shot 2021-09-01 at 6 36 29 PM" src="https://user-images.githubusercontent.com/89918307/131676517-eb7fe348-5268-4d21-81f8-a8da94fb8be5.png">

**Comment by caleighm** [comment]
Hi there! Thanks for reporting this issue. That API will be made public in an upcoming release. In the meantime, we'll update our documentation so it's less confusing.

**Comment by 3embed007** [comment]
Ok thanks for the prompt reply, any idea when is the next release scheduled?

**Comment by caleighm** [comment]
Hi @3embed007 , I can't give exact details on when upcoming releases are scheduled, but this issue is definitely on our radar.

In the meantime, to unblock you, you might try modifying the slot's aspect mode instead of the video. If you're using a full-screen slot, that will actually end up with an identical effect.

**Comment by 3embed007** [comment]
Hi, thanks for the suggestion, i have tried adding **slot.setAspect(BroadcastConfiguration.AspectMode.FILL)**; for a full-screen slot and using _broadcastSession.attachDevice(..._ as per the docs, still the video for me is showing black band on top and bottom on some devices.Basically i'am trying to resolve this issue,when on some devices camera output is not fitting to fullscreen using fill aspect mode, and this issue is therein above sample app also,any help or guidance on how to achieve it shall be highly appreciated.Thanks

**Comment by 3embed007** [comment]
Hi, thanks for the suggestion, i have tried adding **slot.setAspect(BroadcastConfiguration.AspectMode.FILL)**; for a full-screen slot and using _broadcastSession.attachDevice(..._ as per the docs, still the video for me is showing black band on top and bottom on some devices.Basically i'am trying to resolve this issue,when on some devices camera output is not fitting to fullscreen using fill aspect mode, and this issue is therein above sample app also,any help or guidance on how to achieve it shall be highly appreciated.Thanks

**Comment by 3embed007** [comment]
Hi,i was able to resolve that issue, by adding this line--- 

ImagePreviewView preview =
              ((ImageDevice) device).getPreviewView(BroadcastConfiguration.AspectMode.FILL);
Thanks.

**Comment by caleighm** [comment]
Great! Glad you were able to resolve this. I will close this issue, but please let us know if you have more questions!
