### ISSUE TITLE
Watching/Joining stream by other user

### ISSUE THREAD

**Issue by Anu07** [aws-samples/amazon-ivs-broadcast-android-sample#21]
Is this sample capable of allowing a user to join stream created by someone else? If no, Kindly help me with this. How I can achieve it. I have all the authorizations tuff enabled for my channel.

**Comment by caleighm** [comment]
Hi @Anu07, IVS provides a separate SDK specifically for playback/watching streams: https://docs.aws.amazon.com/ivs/latest/userguide/player-android.html

At this time we do not support multiple users streaming to the same channel.

I'm going to close this issue, but let me know if I misunderstood your question and we can continue chatting about it here.
