### ISSUE TITLE
How to make the preview screen full screen

### ISSUE THREAD

**Issue by xlg** [aws-samples/amazon-ivs-broadcast-android-sample#22]
Hi,I have mobile phones with multiple resolutions. On 1080x1920, there will be black borders on the left and right when previewing, and on 1080x2340, there will be black borders on the top and bottom when previewing. I tried tweaking the parameters of BroadcastConfiguration Vec2, but it only seems to have an effect on the launched stream. TextureView has been set to full screen, I guess it is the surface output by the camera, which is not scaled and cropped proportionally. If there is a way to set the preview to be full screen please let me know, thanks.

**Comment by caleighm** [comment]
Hi @xlg, please try getting the preview with the FILL AspectMode:

```
imageDevice.getPreviewView(BroadcastConfiguration.AspectMode.FILL);
```
([ref](https://aws.github.io/amazon-ivs-broadcast-docs/1.3.0/android/reference/com/amazonaws/ivs/broadcast/ImageDevice.html#getPreviewView(com.amazonaws.ivs.broadcast.BroadcastConfiguration.AspectMode)))

You can read more about AspectMode [here](https://aws.github.io/amazon-ivs-broadcast-docs/1.3.0/android/reference/com/amazonaws/ivs/broadcast/BroadcastConfiguration.AspectMode.html).

Hope this helps! Please let us know if you have other questions.

**Comment by xlg** [comment]
Thanks a lot @caleighm ,it worked for me.
Indeed, I also encountered a problem, I raised another [issue](https://github.com/aws-samples/amazon-ivs-broadcast-android-sample/issues/24#issue-1210629294)
