### ISSUE TITLE
How to support landscape mode

### ISSUE THREAD

**Issue by KunNiu** [aws-samples/amazon-ivs-broadcast-android-sample#35]
When switch to landscape, the video looks like the screenshot attached, how to make it fill screen? I already set the aspect to fill.
![Screenshot_20230508-120723](https://user-images.githubusercontent.com/17312834/236732040-f48c7e26-72a9-420b-9094-be246371ece0.png)

**Comment by KunNiu** [comment]
I made such changes in demo, and got simular behavior
<img width="832" alt="图片" src="https://user-images.githubusercontent.com/17312834/236843263-1ee68f0c-d25b-472f-9574-1a8b5a85fc56.png">

<img width="384" alt="图片" src="https://user-images.githubusercontent.com/17312834/236843555-3c5d3d09-d1d1-4ccf-af8b-8f17d5708b03.png">
<img width="331" alt="图片" src="https://user-images.githubusercontent.com/17312834/236843606-23090d09-8d6d-4b6c-bce0-42d26ac9e06c.png">

**Comment by bclymer** [comment]
In the screenshot of the config your last message, it looks like the aspect ratio is being set to `FIT` and not `FILL. Can you confirm the issue still happens when setting to `FILL`?

**Comment by KunNiu** [comment]
Hi @bclymer, thanks for your reply.
The issue still exist after change to FILL

<img width="930" alt="图片" src="https://user-images.githubusercontent.com/17312834/236969738-c8e4243d-507d-4e25-94b3-b85e8acb850b.png">

**Comment by KunNiu** [comment]
Hi @bclymer , do we have any updates here?

**Comment by KunNiu** [comment]
@bclymer thanks. I can solve the issue with your solution, close this issue.
