### ISSUE TITLE
Duplicate class org.webrtc.AddIceObserver in flutter_webrtc and com.amazonaws:ivs-broadcast:1.9.0:stages@aar

### ISSUE THREAD

**Issue by weekend8394** [aws-samples/amazon-ivs-broadcast-android-sample#41]
I've encountered a problem with duplicate classes when using the flutter_webrtc and com.amazonaws:ivs-broadcast:1.9.0:stages@aar libraries together in my Flutter project.

In my pubspec.yaml I have:
flutter_webrtc: ^0.9.33

And in my build.gradle for Android, I have:
implementation('com.amazonaws:ivs-broadcast:1.9.0:stages@aar')

When I attempt to build, I encounter the following error:
Duplicate class org.webrtc.AddIceObserver found in modules jetified-android-104.5112.06-runtime (com.github.webrtc-sdk:android:104.5112.06) and jetified-ivs-broadcast-1.9-stages.0-stages-runtime (com.amazonaws:ivs-broadcast:1.9.0)

I've tried to exclude the org.webrtc module from ivs-broadcast library in build.gradle, but the error persists.
:implementation('com.amazonaws:ivs-broadcast:1.9.0:stages@aar'){
        exclude group: 'org.webrtc', module: 'webrtc'
 }

Could you please provide any guidance or potential solutions to address this issue?

**Comment by dang-tommy** [comment]
Hi @weekend8394, sorry for the late response. We don't currently have a workaround for duplicate WebRTC classes, but we are planning to try to fix this issue in the future. Until that work is done, for now the only solution is to use only one of the two libraries. Sorry for the inconvenience.

**Comment by kvasilye** [comment]
This was fixed a few months ago in version 1.14, and has stayed the same (fix is there) in more recent releases including the 1.16.0 we just published today.

You can now use the IVS Broadcast SDK in the same app with other SDKs which use Google's WebRTC library.

**Comment by baroukh404** [comment]
Are the problem is solved ? 
I have the same issue and I have resolved. Just exclude the webrtc on jitsi meet .

**Comment by weekend8394** [comment]
> Are the problem is solved ? I have the same issue and I have resolved. Just exclude the webrtc on jitsi meet .


Later, we suspended this function first , so we didn’t use it for the time being , LOL

**Comment by kvasilye** [comment]
The naming conflict was solved in IVS Broadcast SDK 1.14

Since that version, you can use the IVS Broadcast SDK + any other SDK which uses Google's WebRTC such as Live Kit
