### ISSUE TITLE
Duplicate class org.webrtc.AddIceObserver when i integrated web rtc

### ISSUE THREAD

**Issue by wohsj110** [aws-samples/amazon-ivs-broadcast-android-sample#53]
could you help me？

**Comment by dang-tommy** [comment]
Hey @wohsj110, unfortunately we don't currently have a solution for symbol conflicts when an app tries to use the SDK with another WebRTC dependency.

**Comment by kvasilye** [comment]
The IVS Broadcast SDK can be used in the same app with other SDKs using Google's WebRTC since IVS Broadcast SDK verison 1.14.0. The current version is 1.16.0.
