### ISSUE TITLE
Is there a way to generate stream key from the SDK?

### ISSUE THREAD

**Issue by AxelDavalosR** [aws-samples/amazon-ivs-broadcast-android-sample#7]
Hi, this tool is amazing. Just checking your repository, it is not an issue, but I have a question:

It assumes you already have the channel and stream key. But is there a way to generate stream keys or the channel itself from the SDK?
or that can be achieved only with the web page where you create channels?

**Comment by bclymer** [comment]
Hi @AxelDavalosR, at the moment we have no plans to add any APIs to manage channels to the SDK. I would recommend running your own backend that communicates with the [IVS API](https://docs.aws.amazon.com/general/latest/gr/ivs.html), and then expose that data securely to your application.
