### ISSUE TITLE
Private Channels Question

### ISSUE THREAD

**Issue by dangolbeeker** [aws-samples/amazon-ivs-broadcast-android-sample#9]
For creating private channels can a single Playback Key be used to sign multiple channels or is the limitation 3 private streams at a time?

**Comment by rbeadles** [comment]
A single playback key can be used on multiple channels. The channel must have playback authentication enabled (https://docs.aws.amazon.com/ivs/latest/userguide/private-channels-enable-playback-auth.html) and when the playback token is signed, the channel ARN must be included in the payload (https://docs.aws.amazon.com/ivs/latest/userguide/private-channels-generate-tokens.html#private-channels-tokens-schema). 

_Please note: For other questions related to IVS (not related to the IVS Broadcast SDK sample applications), we recommend reaching out to AWS Technical Support (https://aws.amazon.com/contact-us/) or AWS re:Post (https://repost.aws/), which is the new version of the AWS Forums._
